<?php

require_once DRUPAL_ROOT . '/includes/locale.inc';
require_once dirname(__FILE__) . '/recent_supporters.api.php';

define ('RECENT_SUPPORTERS_NAME_DISPLAY_DEFAULT', 0);
define ('RECENT_SUPPORTERS_NAME_DISPLAY_FULL', 1);
define ('RECENT_SUPPORTERS_NAME_DISPLAY_INITIAL', 2);
define ('RECENT_SUPPORTERS_NAME_DISPLAY_FIRST_ONLY', 3);

use \Drupal\recent_supporters\Loader;
use \Drupal\polling\UrlGenerator;

function _recent_supporters_name_display_options() {
  return array(
    RECENT_SUPPORTERS_NAME_DISPLAY_DEFAULT => t('Default'),
    RECENT_SUPPORTERS_NAME_DISPLAY_FULL => t('Full name'),
    RECENT_SUPPORTERS_NAME_DISPLAY_INITIAL => t('First name and initial'),
    RECENT_SUPPORTERS_NAME_DISPLAY_FIRST_ONLY => t('First name only'),
  );
}

/**
 * Get the current recent supporter settings.
 */
function recent_supporters_settings() {
  $saved_settings = variable_get('recent_supporters_settings', array()) + array(
    'backend'        => 'webform',
    'query_limit'    => 10,
    'visible_count'  => 6,
    'cycle_toggle'   => 0,
    'country_toggle' => 1,
    'comment_toggle' => 0,
    'name_display'   => RECENT_SUPPORTERS_NAME_DISPLAY_DEFAULT,
  );
  return $saved_settings;
}

/**
 * Implements hook_menu();
 */
function recent_supporters_menu() {
  // Serve a localized ISO -> country-name mapping.
  // If clean URLs are disabled, it will always be served through the menu system.
  // If clean URLs are enabled and it already exists, PHP will be bypassed.
  $dir = _recent_supporters_countries_dir();
  $items[$dir . '/%'] = array(
    'title' => 'Generate JS country mapping',
    'page callback' => 'recent_supporters_country_json',
    'page arguments' => array(count(explode('/', $dir))),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/content/recent-supporters'] = array(
    'title'            => t('Recent Supporter Settings'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('recent_supporters_settings_form'),
    'description'      => 'Recent Supporter settings.',
    'access arguments' => array('administer recent supporters'),
    'file'             => 'recent_supporters.admin.inc',
  );
  $items['admin/config/content/recent-supporters/general'] = array(
    'title' => t('General settings'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function recent_supporters_permission() {
  $permissions['administer recent supporters'] = array(
    'title'       => t('Administer recent supporter settings'),
    'description' => t('Administer site-wide settings for the recent supporters block.'),
  );
  return $permissions;
}

function _recent_supporters_countries_dir() {
  $directory_path = file_stream_wrapper_get_instance_by_scheme('public')->getDirectoryPath();
  return $directory_path . '/countries';
}

function recent_supporters_preprocess_block(&$variables) {
  if (   $variables['block']->module == 'recent_supporters'
      && !empty($variables['block']->block_html_id)) {
    $variables['block_html_id'] = $variables['block']->block_html_id;
  }
}

function recent_supporters_preprocess_html($variables) {
  $langcode = '';
  if (!empty($variables['language'])) {
    $lang = preg_split('/-/', $variables['language']->language);
    $langcode = array_shift($lang);
  }
  // try to load localized timeago library
  // if this fails load the default (not localized) timeago lib
  $library = libraries_detect('timeago');
  if (!empty($library['variants'][$langcode])) {
    libraries_load('timeago', $langcode);
  } else {
    libraries_load('timeago');
  }

  // load jQuery Easing library
  libraries_load('jquery.easing');
}
/**
 * Implements hook_library().
 */
function recent_supporters_library() {
  $path = drupal_get_path('module', 'recent_supporters');
  if (function_exists('libraries_get_path') && file_exists(libraries_get_path('timeago'))) {
    $path = libraries_get_path('timeago');
  }
  return array(
    'timeago' => array(
      'title' => t('Time ago'),
      'website' => 'http://timeago.yarp.com',
      'version' => '1.4.1',
      'js' => array(
        $path . '/jquery.timeago.js',
      ),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function recent_supporters_libraries_info() {
  $library = array(
    'timeago' => array(
      'name' => t('Time ago'),
      'vendor url' => 'http://timeago.yarp.com',
      'download url' => 'https://github.com/rmm5t/jquery-timeago',
      'version arguments' => array(
        'file' => 'jquery.timeago.js',
        'pattern' => '@version\s+([0-9a-zA-Z\.-]+)@',
      ),
      'files' => array(
        'js' => array(
          'jquery.timeago.js',
        ),
      ),
      'variants' => array(),
    ),
    'jquery.easing' => array(
      'name' => t('Time ago'),
      'vendor url' => 'http://gsgd.co.uk/sandbox/jquery/easing/',
      'download url' => 'http://gsgd.co.uk/sandbox/jquery/easing/jquery.easing.1.3.js',
      'version arguments' => array(
        'file' => 'jquery.easing.1.3.js',
        'pattern' => '/jQuery Easing v([0-9a-zA-Z\.]+)/',
        'lines' => 5,
      ),
      'files' => array(
        'js' => array(
          'jquery.easing.1.3.js',
        ),
      ),
    )
  );

  // define all locales as variants of timeago
  foreach (array(
    "ar", "bg", "bs", "ca", "cs", "cy", "da", "de", "el", "en", "en-short", "es", "es-short", "et", "fa", "fi", "fr", "fr-short", "gl", "he", "hr", "hu", "hy", "id", "is", "it", "ja", "jv", "ko", "lt", "mk", "nl", "no", "pl", "pt-br", "pt", "ro", "rs", "ru", "sk", "sl", "sv", "th", "tr", "uk", "uz", "vi", "zh-CN", "zh-TW"
  ) as $variant) {
    $library['timeago']['variants'][$variant] = array(
      'files' => array(
        'js' => array(
          'jquery.timeago.js',
          'locales/jquery.timeago.'.$variant.'.js',
        ),
      ),
    );
  }

  return $library;
}

/**
 * Implements hook_block_info().
 */
function recent_supporters_block_info() {
  $info = array(
    'recent_supporters' => array(
      'info'   => t('Recent supporters'),
      'region' => 'sidebar_second',
    ),
    'recent_supporters_all_actions' => array(
      'info'   => t('Recent supporters accumulated for all action pages'),
      'region' => 'sidebar_second',
    ),
  );
  return $info;
}

/**
 * Implements hook_block_view().
 */
function recent_supporters_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'recent_supporters':
      $block = _recent_supporters_block_recent_supporters();
      break;
    case 'recent_supporters_all_actions':
      $block = _recent_supporters_block_recent_supporters_all_actions();
      break;
  }
  return $block;
}

/**
 * Implements hook_polling_field_type_plugin_info().
 */
function recent_supporters_polling_field_type_plugin_info() {
  $info['recent_supporters'] = [
    '\\Drupal\\recent_supporters\\FieldPolling',
  ];
  return $info;
}

/**
 * Implements hook_polling_global_plugin_info().
 */
function recent_supporters_polling_global_plugin_info() {
  return ['\\Drupal\\recent_supporters\\GlobalPolling'];
}

/**
 * creates content for a recent supporters block for 1 specific action;
 * called from hook_block_view();
 */
function _recent_supporters_block_recent_supporters() {
  $block = array();
  if (($node = menu_get_object()) == FALSE || isset($node->nid) == FALSE) {
    return NULL;
  }

  /* thank_you_page integration */
  if (   $node->type == "thank_you_page"
      && isset( $_GET['share']) == TRUE
      && preg_match('@node/(\d+)@', $_GET['share'], $get_nid) == 1) {
    $nid = $get_nid[1];
    $node = node_load($nid);
  }
  if ($node === FALSE) {
    return NULL;
  }

  // read field settings from the site we are ON
  // and not any related action site (in case we are on a thank_you_page
  // therefore: load the field prior to reloading the node
  list($items, $instance, $field) = recent_supporters_first_field('node', $node, 'recent_supporters');
  if (!$field) {
    return;
  }

  $lang = $GLOBALS['language']->language;
  $block['subject'] = t('Recent supporters');
  $block['content'] = recent_supporters_field_formatter_view('node', $node, $field, $instance, $lang, $items, []);
  return $block;
}

/**
 * Helper function to get all installed action content types as
 * well as their default recent supporters texts
 */
function _recent_supporters_get_types_defaults($lang_code = NULL) {
  global $language;

  $saved_lang = $language;
  if (isset($lang_code)) {
    $language_list = language_list();
    $language      = $language_list[$lang_code];
  }
  $types = array();
  foreach (entity_get_info()['node']['bundles'] as $type => $info) {
    if (!empty($info['recent_supporters'])) {
      $types[$type] = [
        'enabled' => 1,
        'text' => $info['recent_supporters']['default_text'],
      ];
    }
  }
  $language = $saved_lang;

  return $types;
}

/**
 * creates content for a recent supporters block for all configured
 * action pages with configured texts;
 * called from hook_block_view();
 */
function _recent_supporters_block_recent_supporters_all_actions() {
  $block = array();
  $saved_settings = recent_supporters_settings();
  $types_settings = variable_get('recent_supporters_settings_types', array())
    + _recent_supporters_get_types_defaults($GLOBALS['language']->language);
  $types = array();
  foreach ($types_settings as $type => $setting) {
    if ($setting['enabled']) {
      $types[] = $type;
    }
  }

  $backend = Loader::instance()->getBackend($saved_settings['backend']);
  $params = $backend->buildParams($saved_settings, NULL, $types);

  $supporters  = $backend->recentOnAllActions($params);
  $texts = _recent_supporters_get_action_texts($types);

  $id = drupal_html_id('recent-supporters');
  $block['subject'] = t('Recent supporters');
  $block['content'] = array(
    '#theme'        => 'recent_supporters',
    '#id'           => $id,
    '#supporters'   => $supporters,
    '#show_country' => ($saved_settings['country_toggle'] == '1') ? TRUE : FALSE,
    '#show_comment' => ($saved_settings['comment_toggle'] == '1') ? TRUE : FALSE,
    '#all_actions'  => TRUE,
    '#texts'        => $texts,
    '#visible_count' => $saved_settings['visible_count'],
  );

  // set configured texts in generic recentSupporter setting
  drupal_add_js(
    array(
      'recentSupporters' => array(
        'actionTexts'    => $texts,
      )
    ),
    'setting'
  );

  // set an unique id to use as key in Drupal.settings array
  // and fill with block specific settings
  drupal_add_js(array('recentSupporters' => array(
    'blocks' => array(
      $id => array(
        'pollingURL'      => UrlGenerator::instance()->globalUrl(),
        'cycleSupporters' => $saved_settings['cycle_toggle'],
        'showCountry'     => $saved_settings['country_toggle'],
        'showComment'     => $saved_settings['comment_toggle'],
        'visibleCount'    => $saved_settings['visible_count'],
        'allActions'      => TRUE,
      ),
    ),
  )),'setting');

  if ($saved_settings['country_toggle']) {
    $dir = _recent_supporters_countries_dir();
    drupal_add_js($dir . '/' . $GLOBALS['language']->language . '.js', array('scope' => 'footer', 'preprocess' => FALSE));
  }
  return $block;
}

/**
 * Page callback for country Javascript.
 */
function recent_supporters_country_json($filename) {
  $langCode = substr($filename, 0, strlen($filename) - 3);
  $languages = language_list();
  if (isset($languages[$langCode])) {
    $GLOBALS['language'] = $languages[$langCode];
  }
  else {
    return MENU_ACCESS_DENIED;
  }

  $target = 'public://countries/' . $langCode . '.js';
  $target_dir = dirname($target);
  if (!file_prepare_directory($target_dir, FILE_CREATE_DIRECTORY | FILE_MODIFY_PERMISSIONS)) {
    watchdog('recent_supporters', 'Unable to create directory: !dir.', array('!dir' => $target_dir), WATCHDOG_ERROR);
    return NULL;
  }

  $countries = country_get_list();
  $output = 'Drupal.settings.recentSupporters.countries = ' . drupal_json_encode($countries) . ';';
  file_put_contents($target, $output);
  file_transfer($target, array('Content-Type' => 'text/javascript', 'Content-Length' => filesize($target)));
}

/**
 * Implements hook_theme().
 */
function recent_supporters_theme() {
  $theme['recent_supporters'] = array(
    'variables' => array(
      'id' => '',
      'supporters' => array(),
      'show_country' => FALSE,
      'show_comment' => FALSE,
      'all_actions' => FALSE,
      'texts' => array(),
      'visible_count' => 5,
    ),
  );
  return $theme;
}

/**
 * Theme preprocess function for theme_recent_supporters().
 */
function recent_supporters_preprocess_recent_supporters(&$variables) {
  $s = &$variables['supporters'];
  $s = array_splice($s, 0, $variables['visible_count']);
}

/**
 * theme function for theme('recent_supporters', $variables).
 */
function theme_recent_supporters($variables) {
  $supporters = $variables['supporters'];
  if ($show_country = $variables['show_country']) {
    $countries = country_get_list();
  }
  $output = '';

  if (count($supporters) < 1) {
    $output = '<div class="no-activity-yet">'.t('No recent activity.').'</div>';
    return $output;
  }
  else {
    $all_actions = $variables['all_actions'] ? 'recent-supporters-all-actions' : 'recent-supporters-single-action';
    $texts = $variables['texts'];
    $output .= "<div id=\"{$variables['id']}\" class=\"recent-supporters-wrapper\">";
    $output .= "<ul class=\"recent-supporters $all_actions\">\n";
    foreach($supporters as $supporter) {
      $action_type = "";
      if (!empty($supporter['action_type'])) {
        $action_type = "action-type-" . $supporter['action_type'];
      }
      $output .= "<li class=\"supporter clearfix $action_type\">\n";

      if ($variables['show_comment'] && !empty($supporter['comment'])) {
        $output .= "\n<span class=\"comment\">{$supporter['comment']}</span>\n";
      }

      if ($show_country) {
        $country_code = empty($supporter['country']) ? 'no-cc' : $supporter['country'];
        $country_name = $country_code == 'no-cc' ? '' : $countries[$country_code];
        $classes = "flag-".strtolower(drupal_clean_css_identifier($country_code));
        $output .= "<span title=\"".t($country_name)
          ."\" class=\"country flag " . $classes ."\">";
        $output .= $country_code;
        $output .= "</span>\n";
      }
      if ($variables['all_actions']) {
        $first_name = $supporter['first_name'] . (!empty($supporter['first_name']) ? " " : "");
        $vars['!supporter_name'] = "<span class=\"name\">" . $first_name . "<span class=\"last_name\">" . $supporter['last_name'] . "</span></span>\n";
        $vars['!action_title']   = "<span class=\"title\">";
        if (!empty($supporter['action_url'])) {
          $vars['!action_title']  .= '<a href="'.$supporter['action_url'].'" ';
          $vars['!action_title']  .= 'title="'.$supporter['action_title'].'">';
          $vars['!action_title']  .= $supporter['action_title'];
          $vars['!action_title']  .= '</a>';
        } else {
          $vars['!action_title']  .= $supporter['action_title'];
        }
        $vars['!action_title']  .= "</span>";
        $output .= format_string($texts[$supporter['action_type']], $vars);
      }
      else {
        $output .= "<span class=\"name\">";
        $output .= implode(" ", array($supporter['first_name'], $supporter['last_name']));
        $output .= "</span>\n";
      }
      $output .= "\n<span class=\"time\" data-timestamp=\"".$supporter['timestamp']."\" title=\"".$supporter['rfc8601']."\">";
      $output .= date('d.m.Y H:i', $supporter['timestamp']);
      $output .= "</span>\n";

      $output .= "</li>\n";
    }
    $output .= "</ul></div>\n";
  }
  return $output;
}

/**
 * callback funtion
 */
function _recent_supporters_strip_callback($value) {
  return mb_substr($value, 0, 1);
};

/**
 * helper function: get the configured action texts
 * returns only the texts for the types in the parameter, or all if the parameter is an empty array
 */
function _recent_supporters_get_action_texts($types = array()) {
  static $texts;

  if (!isset($texts)) {
    $texts = variable_get('recent_supporters_settings_types', _recent_supporters_get_types_defaults());
  }
  if (!empty($types)) {
    $filtered_types = array_intersect_key($texts, array_flip($types));
  } else {
    $filtered_types = $texts;
  }
  $result = array();
  // set a new array with the values we also want to expose via JSON or Drupal.settings
  // we do *not* want to expose the variable values as a whole
  foreach ($filtered_types as $type => $value) {
    $result[$type] = $value['text'];
  }
  return $result;
}

/**
 * Implements hook_field_widget_form().
 */
function recent_supporters_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $item = isset($items[$delta]) ? $items[$delta] : array();
  if (isset($instance['default_value'][$delta]) && !isset($items[$delta])) {
    $item = $instance['default_value'][$delta];
  }

  $defaults = array(
    'toggle' => 0,
    'options' => array(
      'visible_count' => 6,
      'cycle_toggle' => 0,
      'country_toggle' => 1,
      'comment_toggle' => 0,
      'name_display' => RECENT_SUPPORTERS_NAME_DISPLAY_DEFAULT,
    ),
  );

  $item = drupal_array_merge_deep($defaults, $item);

  $toggle_id = drupal_html_id('recent-supporters-toggle');
  $element['toggle'] = array(
    '#title' => t('Display a recent supporters block.'),
    '#description' => t('Display a recent supporters block.'),
    '#type' => 'checkbox',
    '#default_value' => $item['toggle'],
    '#id' => $toggle_id,
  );
  $element['options'] = array(
    '#type' => 'fieldset',
    '#title' => t('Recent supporters advanced settings.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#states' => array(
      'visible' => array(
        "#$toggle_id" => array('checked' => TRUE),
      ),
    ),
  );
  $element['options']['name_display'] = array(
    '#title' => t('Supporter name display'),
    '#description' => t('Configure the information displayed about the supporters of this action.'),
    '#type' => 'select',
    '#options' => _recent_supporters_name_display_options(),
    '#attributes' => array(),
    '#default_value' => $item['options']['name_display'],
  );
  $element['options']['visible_count'] = array(
    '#title' => t('Number of max. visible supporters.'),
    '#description' => t('Number of max. visible supporters.'),
    '#type' => 'textfield',
    '#size' => 12,
    '#maxlength' => 10,
    '#attributes' => array(),
    '#default_value' => $item['options']['visible_count'],
  );
  $element['options']['cycle_toggle'] = array(
    '#title' => t('Cycle supporters.'),
    '#description' => t('Cycle supporters.'),
    '#type' => 'checkbox',
    '#default_value' => $item['options']['cycle_toggle'],
  );
  $element['options']['country_toggle'] = array(
    '#title' => t('Show country of supporters.'),
    '#description' => t('Show country of supporters.'),
    '#type' => 'checkbox',
    '#default_value' => $item['options']['country_toggle'],
  );
  $element['options']['comment_toggle'] = array(
    '#title' => t('Show user comments.'),
    '#description' => t('Show the comment from the comment field.'),
    '#type' => 'checkbox',
    '#default_value' => $item['options']['comment_toggle'],
  );

  return $element;
}

/**
 * Implements hook_field_info().
 */
function recent_supporters_field_info() {
  $info['recent_supporters'] = array(
    'label' => t('Recent supporters'),
    'description' => t('Allows you to display a recent supporters block.'),
    'settings' => array('style' => NULL),
    'default_widget' => 'recent_supporters',
    'default_formatter' => 'recent_supporters',
  );
  return $info;
}

/**
 * Implements hook_field_widget_info().
 */
function recent_supporters_field_widget_info() {
  $info['recent_supporters'] = array(
    'label' => t('Recent supporters'),
    'field types' => array('recent_supporters'),
    'settings' => array('size' => 60),
    'behaviors' => array(
      'multiple values' => FIELD_BEHAVIOR_DEFAULT,
      'default values' => FIELD_BEHAVIOR_DEFAULT,
    ),
  );
  return $info;
}

/**
 * Implements hook_field_formatter_info().
 */
function recent_supporters_field_formatter_info() {
  $info['recent_supporters'] = array(
    'label' => 'Recent supporters',
    'field types' => array('recent_supporters'),
  );
  return $info;
}

/**
 * Implements hook_field_presave().
 */
function recent_supporters_field_presave($entity_type, $entity, $field, $instance, $langcode, &$items) {
  if ($field['type'] == 'recent_supporters') {
    foreach ($items as &$item) {
      if (is_array($item['options'])) {
        $item['options'] = serialize($item['options']);
      }
    }
  }
}

/**
 * Implements hook_field_load().
 */
function recent_supporters_field_load($entity_type, $entities, $field, $instances, $langcode, &$items, $age) {
  if ($field['type'] == 'recent_supporters') {
    foreach ($entities as $id => $entity) {
      foreach ($items[$id] as &$item) {
        $item['options'] = unserialize($item['options']);
      }
    }
  }
}

/**
 * Implements hook_field_is_empty().
 */
function recent_supporters_field_is_empty($item, $field) {
  return FALSE;
}

/**
 * Implements hook_field_formatter_view().
 */
function recent_supporters_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $entity_id = entity_id($entity_type, $entity);
  $field_name = $field['field_name'];
  $polling_url = UrlGenerator::instance()->entityUrl($entity_type, $entity_id);

  $output = [];
  foreach ($items as $delta => $item) {
    $show = isset($item['toggle']) ? $item['toggle'] : 0;

    if ($show) {
      // save values for polling
      $options = $item['options'] + recent_supporters_settings();
      $backend = Loader::instance()->getBackend($options['backend']);
      $id = drupal_html_id('recent-supporters');

      $params = $backend->buildParams($options, $entity);
      $supporters = $backend->recentOnOneAction($params);
      $content = array(
        '#theme' => 'recent_supporters',
        '#id' => $id,
        '#supporters' => $supporters,
        '#show_country' => (bool) $options['country_toggle'],
        '#show_comment' => (bool) $options['comment_toggle'],
        '#all_actions' => FALSE,
        '#texts' => NULL,
        '#visible_count' => $options['visible_count'],
      );

      // set an unique id to use as key in Drupal.settings array
      drupal_add_js(array('recentSupporters' => array(
        'blocks' => array(
          $id => array(
            'cycleSupporters' => $options['cycle_toggle'],
            'showCountry' => $options['country_toggle'],
            'showComment' => $options['comment_toggle'],
            'visibleCount' => $options['visible_count'],
            'field_name' => $field_name,
            'delta' => $delta,
            'allActions' => FALSE,
            'pollingURL' => $polling_url,
          )
        )
      )), 'setting');

      if ($options['country_toggle']) {
        $dir = _recent_supporters_countries_dir();
        drupal_add_js($dir . '/' . $langcode . '.js', array('scope' => 'footer', 'preprocess' => FALSE));
      }
      $output[] = $content;
    }
  }
  return $output;
}

/**
 * utility function: returns all field items by field type in array
 * (indexed by field name)
 */
function recent_supporters_first_field($entity_type, $node, $field_type) {
  $instances = field_info_instances($entity_type, $node->type);
  $recent_supporter_fields = array();
  foreach ($instances as $instance) {
    $field = field_info_field($instance['field_name']);
    if ($field['type'] == $field_type) {
      $items = field_get_items($entity_type, $node, $instance['field_name']);
      if ($items) {
        return [$items, $instance, $field];
      }
    }
  }
  return [NULL, NULL, NULL];
}
